### ISSUE TITLE
Preset message for sending address, phone, clinic timings that can be sent to 1 patient (from edit-sched)

### ISSUE THREAD

**Issue by apoorvumang** [apoorvumang/mummy-software#17]

**Comment by anuragmahima** [comment]
about the visit log, can it be just for consultation visits,
If it shows the vaccination log also how to differentiate vaccination ws done by me or someone else.
vaccination also doesn't have delete feature.

**Comment by apoorvumang** [comment]
Obsolete, fix might be part of #26
