### ISSUE TITLE
visit log as excel sheet, on patients' ID

### ISSUE THREAD

**Issue by anuragmahima** [apoorvumang/mummy-software#22]
1 Date	
2 Weight (KG)	
3 Height (CM)	
4 BMI = Wt(kg)/ Ht(cm)/Ht(cm)*10000 (KG/M2)
5 Symptoms  : a drop down list of complaints by patient	
6 Signs :	Examination findings 
7 Diagnosis	
8 Nature of services : options OPD & Vaccinations (a drop down list of vaccines	where multiple options are possible
9 Nature of Transactions   :Cash/ card/ Pay TM/ 
10 Amount Received: Rs.
11 Remarks	
12 Generate Bill  a button to generate a bill which has Name/ ID/ Nature of services/ Amount recd/ Nature of transaction.
13. Edit/ Delete visit button

**Comment by apoorvumang** [comment]
Part of #26
